export default function Page() {
    return (
        <div>
            <h1 className="text-3xl font-bold text-center text-red-500 py-10">User Page</h1>
        </div>
    );
}

export async function generateMetadata() {
    return {
        title: "User Page",
        description: "Generated by create next app",
    };
}
